image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

# Build-Job
build-job:
  stage: build
  script:
    - cd CalculatorApp
    - dotnet restore
    - echo "Compiling the code..."
    - dotnet build --no-restore
    - echo "Compile complete."


unit-test-job:
  stage: test
  script:
    - echo "Running 7 unit tests... This will take about 60 seconds."
    - cd CalculatorTests
    - dotnet build  
    - mkdir -p TestResults  # Stelle sicher, dass das TestResults-Verzeichnis existiert
    - dotnet test --no-build --logger "trx;LogFileName=TestResults/test_results.xml"  # Speichere die Testergebnisse als XML-Datei
    - echo "Listing contents of TestResults"
    - ls -la TestResults
  artifacts:
    when: always
    paths:
      - CalculatorTests/TestResults/ 
    reports:
      junit: CalculatorTests/TestResults/test_results.xml



# Linting-Job
lint-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - dotnet build /p:StyleCopTreatErrorsAsWarnings=false
    - echo "No lint issues found."
  allow_failure: false
  only:
    - main

# Deployment-Job
deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
