image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd CalculatorApp
    - dotnet restore
    - echo "Compiling the code..."
    - dotnet build --no-restore
    - 'dotnet build --no-restore'
    - echo "Compile complete."


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running 7 unit tests... This will take about 60 seconds."
    - cd CalculatorTests  
    - dotnet test --no-build --logger "trx;LogFileName=test_results.trx"
  artifacts:
    when: always
    paths:
      - CalculatorTests/TestResults/   #pfad testen. 
    reports:
      junit: CalculatorTests/TestResults/*.trx


lint-job:    # It can run at the same time as unit-test-job (in parallel).
  stage: test   # This job also runs in the test stage.
  script:
    - echo "Linting code... This will take about 10 seconds."
    - dotnet build /p:StyleCopTreatErrorsAsWarnings=false
    - echo "No lint issues found."
  allow_failure: false
  only:
    - main





deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."


