image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

# Build-Job
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd CalculatorApp
    - dotnet restore
    - echo "Compiling the code..."
    - dotnet build --no-restore
    - echo "Compile complete."

# Unit-Test-Job
unit-test-job:
  stage: test
  script:
    - echo "Running 7 unit tests... This will take about 60 seconds."
    - cd CalculatorTests
    - dotnet build  
    - mkdir -p CalculatorTests/TestResults  # Erstellt das TestResults-Verzeichnis, falls es nicht existiert
    - dotnet test --no-build --logger "trx;LogFileName=CalculatorTests/TestResults/test_results.trx"
    - echo "Listing contents of CalculatorTests/bin/Debug/net8.0"
    - ls -la CalculatorTests/bin/Debug/net8.0
  artifacts:
    when: always
    paths:
      - CalculatorTests/bin/Debug/net8.0/TestResults/  # Das Verzeichnis für die Test-Ergebnisse
    reports:
      junit: CalculatorTests/bin/Debug/net8.0/TestResults/*.trx  # Lade die .trx Datei hoch

# Linting-Job
lint-job:    # It can run at the same time as unit-test-job (in parallel).
  stage: test   # This job also runs in the test stage.
  script:
    - echo "Linting code... This will take about 10 seconds."
    - dotnet build /p:StyleCopTreatErrorsAsWarnings=false
    - echo "No lint issues found."
  allow_failure: false
  only:
    - main




# Deployment-Job
deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
